version: '3.3'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: movie1234
      MYSQL_DATABASE: movie_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80